//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLTV.View_Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Role
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Role()
        {
            this.Users = new HashSet<User>();
        }
    
        public int IdRole { get; set; }
        public string RoleName { get; set; }
        public Nullable<bool> ViewAll { get; set; }
        public Nullable<bool> ViewUser { get; set; }
        public Nullable<bool> ViewDocGia { get; set; }
        public Nullable<bool> ViewSachMuon { get; set; }
        public Nullable<bool> ViewSach { get; set; }
        public Nullable<bool> ViewThongKe { get; set; }
        public Nullable<bool> AddAll { get; set; }
        public Nullable<bool> AddUser { get; set; }
        public Nullable<bool> AddDocGia { get; set; }
        public Nullable<bool> AddSachMuon { get; set; }
        public Nullable<bool> AddSach { get; set; }
        public Nullable<bool> AddThongKe { get; set; }
        public Nullable<bool> EditAll { get; set; }
        public Nullable<bool> EditUser { get; set; }
        public Nullable<bool> EditDocGia { get; set; }
        public Nullable<bool> EditSachMuon { get; set; }
        public Nullable<bool> EditSach { get; set; }
        public Nullable<bool> DeleteAll { get; set; }
        public Nullable<bool> DeleteUser { get; set; }
        public Nullable<bool> DeleteDocGia { get; set; }
        public Nullable<bool> DeleteSachMuon { get; set; }
        public Nullable<bool> DeleteSach { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User> Users { get; set; }
    }
}
