//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLTV.View_Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sach
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sach()
        {
            this.MuonSaches = new HashSet<MuonSach>();
        }
    
        public string MaSach { get; set; }
        public string TenSach { get; set; }
        public DateTime NamXuatBan { get; set; }
        public int SoTrang { get; set; }
        public int TongSoSach { get; set; }
        public byte[] ImageSach { get; set; }
        public string MaTacGia { get; set; }
        public string MaTheLoai { get; set; }
        public string MaNXB { get; set; }
        public int LuongDaMuon { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MuonSach> MuonSaches { get; set; }
        public virtual NhaXB NhaXB { get; set; }
        public virtual TacGia TacGia { get; set; }
        public virtual TheLoai TheLoai { get; set; }
    }
}
